export const ADD_CONTACT = 'ADD_CONTACT'
export const DELETE_CONTACT = 'DELETE_CONTACT'
export const CHANGE_FAVORITE = 'CHANGE_FAVORITE'
export const CHANGE_CONTACT = 'CHANGE_CONTACT'
export const CHANGE_STATUS = 'CHANGE_STATUS'
export const ADD_STATUS = 'ADD_STATUS'
export const REPLACEMENT_STATUS = 'REPLACEMENT_STATUS'
export const DELETE_STATUS = 'DELETE_STATUS'
export const CHANGE_STATUS_CARD = 'CHANGE_STATUS_CARD'


export const SET_BOOT = 'SET_BOOT'
export const SET_FILTERED_CONTACTS = 'SET_FILTERED_CONTACTS'
